# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28329b795d2eb217c5b27f4729994e9b0c866bb0d645289f45279c47397d2115166eb00294873c86528eac927c811f235da7611b200c49259a80f297dde4e967

test:
  secret_key_base: 9d5a09e31359b559156a17003392d2d66b663a20edf1f69cf75fa07fd12edc4bc535cb1e4f9db1a3c543d083791f2bf68e93a29ee3cab541f3063686271114e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
